### ISSUE TITLE
LD Wizard no longer creates subject IRIs

### ISSUE THREAD

**Issue by wouterbeek** [pldn/LDWizard#144]
### Observed

LD Wizard no longer creates subject IRIs but blank nodes.

### Expected

Subject IRIs to be generated.

### MWE

1. Go through the LD Wizard with any input CSV.
2. Download the RDF at the end.
3. Observe that no subject IRIs appear in the file.

**Comment by wouterbeek** [comment]
After some investigation, we believe that this bug was introduced with the switch to RocketRML. If this is correct, then this bug was introduced in 2.1.0 and did not occur in 2.0.0.

I am unable to test this hypothesis, since I cannot get 2.1.0 operational.

**Comment by vemonet** [comment]
Hi @wouterbeek, indeed blank nodes are generated instead of URIs, but only when "Row number" is chosen for the Key Column (whenever you use a column as key column you will get URIs)

This is due to the fact that there is no standard way to access the CSV row number in RML. So we cannot write a RML mapping that uses the row number to build the Subject URI (afaik). So we use a workaround by defining the Subject of the TripleMap as a blank node, and it works well for us since the blank node number matches the row number after transformation with RocketRML

The changes in the RML script generation to use blank node has been done by @philipperenzen (probably to fix some issues related to the switch to RocketRML, thanks I did not noticed that!)

Is it really important that the TriplesMap are URI and not blank node? Does this break already existing use-cases? If not, imo it would make sense to use blank node for using row number as key

Otherwise to get URIs + row number as subject of the TripleMap, we will need to check in RocketRML if there is a way to access the row number to build the URI. There is nothing about it in the RML specs, so I don't know if RocketRML made the row number available in the RML. If it is not present, we will need to check with the RocketRML if we can add it

**Comment by philipperenzen** [comment]
This has been resolved in version 3.0.0: 
* LDWizard will now create an IRI for each row number instead of blank nodes, for example `<https://data.pldn.nl/8f6052/id/1>` as the subject IRI.

Please feel free to reopen this issue if it persists.
