### ISSUE TITLE
ColumnRefinement returns strings instead of URIs

### ISSUE THREAD

**Issue by EnnoMeijers** [pldn/LDWizard#149]
For the NDE version we are using the ColumnRefinement for automatic lookups through the Network-of-Terms. If successful the result is written to output file. Currently the results is written as a string (like "http://vocab.getty.edu/aat/300212636") instead of a URI (<http://vocab.getty.edu/aat/300212636>). 

See https://github.com/netwerk-digitaal-erfgoed/LDWizard-ErfgoedWizard/blob/update/config.ts for details on our configuration.

**Comment by philipperenzen** [comment]
Hello Enno, 

This has been resolved in version 3.0.0: 
* by default LDWizard will return an IRI that uses the default IRI (unless specified otherwise) with the csv value at the end, like it used to. This would look somewhat like this after the configuration step: `https://data.pldn.nl/8f6052/def/{csv_value}`
* within column refinements it can be specified if a transformation should return an IRI or literal with `yieldsLiteral` or `yieldsIri`.

Please feel free to reopen this issue if it persists.

**Comment by EnnoMeijers** [comment]
Thanks for these changes, when I want to use the yieldsLiteral or yieldsIri in my config.ts for my LDWizard-Erfgoed version (after upgrading to the 3.0.0 and running the yarn install command) I get a 'does not exists in type'  error. May be an update of https://github.com/pldn/LDWizard/blob/main/types/WizardConfig.d.ts is also needed?

**Comment by philipperenzen** [comment]
The typings in this file were indeed not correctly updated, thank you for bringing this to our attention. 

We've released a patch version: LDWizard v3.0.1, which should resolve the typing error you encountered. 

Please update to v3.0.1, and feel free to to reopen this issue if you encounter any more issues. Thank you for your feedback!

**Comment by EnnoMeijers** [comment]
Thanks, this is did solve the problem indeed!
