### ISSUE TITLE
Support for large refinements

### ISSUE THREAD

**Issue by wouterbeek** [pldn/LDWizard#32]
# Observed

Some users choose to refine a table with thousands of rows.  This results in thousands of HTTP requests.  There are two issues with this:

  1. Because all refinement requests are sent at the same moment, some requests fail.
  2. Because many refinement requests are waited for, the user sees the grey waiting page for a longer period of time (see screenshot).

![Screenshot from 2021-06-28 09-14-57](https://user-images.githubusercontent.com/1685012/123596970-138d8a80-d7f3-11eb-9e9a-2dab5d1a0ce4.png)

# Suggestions

1. Do not send all refinement requests at once, but process them over time in a queue.
2. Show the queue progress to the user.

**Comment by wouterbeek** [comment]
https://www.w3.org/community/reports/reconciliation/CG-FINAL-specs-0.2-20230410/

**Comment by philipperenzen** [comment]
From the suggestions:
1. Do not send all refinement requests at once, but process them over time in a queue.
2. Show the queue progress to the user.

---------------------
**Suggestion 1:**
Bulk processing is added in version 3.0.4 using `bulkTransformation`, which also supports large refinements with SPARQL using `bulkSparql` (#151 & #152). Originally, requests from a `transformation`function were done for each value in a a row, one by one. Now with `bulkTransformation`, an entire column with it's values can be transformed, or this can be done in batches (e.g. 5 rows at a time).

---------------------
**Suggestion 2:**
Regarding the progress bar for UI, this is difficult as the RocketRML library does not support a progress status during the transformation and since this transformation is done at once, given the RML mappings and the inputFiles (the refined CSV matrix) we cannot monitor how far the progress is in this stage (unless we would loop over each row of the refined CSV to do a RML transformation, but this would result in a lot of function calls and probably slowing down LDWizard). I have thus made a request for this feature in the RocketRML repository https://github.com/semantifyit/RocketRML in https://github.com/semantifyit/RocketRML/issues/45. 

The progress report consists thus of two parts: 
1. the transformations to create the refined CSV (this can be implemented) 
2. the Rocket RML transformation (need to await feature https://github.com/semantifyit/RocketRML/issues/45) 

If this issue concerns the implementation of a reconciliation feature, please feel  free to adjust the title and description or create a new issue.

**Comment by philipperenzen** [comment]
Added the percentage of progress w.r.t. the transformations done for each column in #156 -  since the the Rocket RML transformation feature is still needs to be implemented, I will close this issue for now and reopen once this feature is supported.

If this issue concerns the implementation of a reconciliation feature, please feel free to reopen the issue and adjust the title and description or create a new issue.
